/* automatically generated by rust-bindgen 0.72.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod mozilla {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub mod phc {
            #[allow(unused_imports)]
            use self::super::super::super::root;
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct AddrInfo {
                _unused: [u8; 0],
            }
            pub const PHCState_OnlyFree: PHCState = 0;
            pub const PHCState_Enabled: PHCState = 1;
            pub type PHCState = ::std::os::raw::c_int;
            unsafe extern "C" {
                #[link_name = "\u{1}?SetPHCState@phc@mozilla@@YAXW4PHCState@12@@Z"]
                pub fn SetPHCState(aState: root::mozilla::phc::PHCState);
            }
            unsafe extern "C" {
                #[link_name = "\u{1}?IsPHCAllocation@phc@mozilla@@YA_NPEBXPEAVAddrInfo@12@@Z"]
                pub fn IsPHCAllocation(
                    arg1: *const ::std::os::raw::c_void,
                    arg2: *mut root::mozilla::phc::AddrInfo,
                ) -> bool;
            }
        }
    }
}
